### ISSUE TITLE
Step 1 Of Many / Project Checkpoint 1 

### ISSUE THREAD

**Issue by smdunn921** [jer179/Avatar#1]
Hey all! 
Don't forget that for Project Checkpoint 1, you'll want to 

- [x] Set up a ReadMe so that people who come to this github page know what's going on. it's as simple as talking about what your project will be about and you can change it if you need as time goes on

- [x] Make a new issue or reply to *this* issue to figure out a good time for team meetings. These will be an important part to make sure that everyone is keeping up with their assigned tasks and generally just keeping the project on track for future checkpoints. This will also be a good time to further hash out any arguments, concerns, ideas, etc. that you have for the project that you may not be able to clearly communicate in any other way. (Not that you don't have a perfectly usable issues board here :wink: )

- [x] This isn't necessarily for the first checkpoint, but you'll want to start finding the texts you plan to work with.

- [x] Finally make sure (if you've not already) that you are getting a clear sense of the research question you want to focus on.

I'm so excited to be the student advisor on this project. Don't be afraid to reach out if you need anything!!

@jer179 @khope168 @mjo43

**Comment by jer179** [comment]
Thanks Shannon! I'd like to start thinking about what exactly the project is going to entail. Like I said, there could be many possibilities as to what direction it could go in, and I'd like to hear what you guys think! 

For meeting times, the best times for me to meet would be weekdays anytime after 4 pm, and I could also do Fridays before 2 pm. Weekends will vary for me, but I can make time for a meeting then if need be. I do work some weekdays at 4, but my shifts change every week so we can just figure out which days will be best!

**Comment by mjo43** [comment]
Could we use slack/teams or some type of messaging service to communicate? Email isn’t the best way to do it

Sent from my iPhone

On Sep 15, 2020, at 4:27 PM, jer179 <notifications@github.com> wrote:

﻿

Thanks Shannon! I'd like to start thinking about what exactly the project is going to entail. Like I said, there could be many possibilities as to what direction it could go in, and I'd like to hear what you guys think!

For meeting times, the best times for me to meet would be weekdays anytime after 4 pm, and I could also do Fridays before 2 pm. Weekends will vary for me, but I can make time for a meeting then if need be. I do work some weekdays at 4, but my shifts change every week so we can just figure out which days will be best!

**Comment by jer179** [comment]
That's true, we could just make a group-chat on our phones if that would work for everyone? I feel like that'd probably be the easiest

**Comment by mjo43** [comment]
Unless someone doesn’t have an iPhone. It’d be nice to see who has read/seen a message. I’m fine with anything. My number is (412) 607-4152

Sent from my iPhone

On Sep 15, 2020, at 5:52 PM, jer179 <notifications@github.com> wrote:

﻿

That's true, we could just make a group-chat on our phones if that would work for everyone? I feel like that'd probably be the easiest

**Comment by smdunn921** [comment]
hi i am here to maybe discourage everyone from sharing their phone numbers on here as this is a public repository, unless you're all cool with strangers potentially seeing your phone numbers. Alternatively, you could all email me your numbers and I can create a group or something (-:

**Comment by mjo43** [comment]
Nice. Is my message able to be deleted then

Sent from my iPhone

On Sep 15, 2020, at 9:44 PM, Shannon Dunn <notifications@github.com> wrote:

﻿

hi i am here to maybe discourage everyone from sharing their phone numbers on here as this is a public repository, unless you're all cool with strangers potentially seeing your phone numbers. Alternatively, you could all email me your numbers and I can create a group or something (-:

**Comment by khope168** [comment]
Hi, I'm finally here! Maybe since this is focused on Avatar we could detail Zuko's redemption arc? It's one of the most iconic redemptions in TV history, I know I'd enjoy it but I'm not sure about you all. 

Meeting times I can do Tuesdays and Thursdays after 4. My schedule is a bit packed this semester so I don't have much wiggle room.

**Comment by haggis78** [comment]
Hi all. I'm glad to see things up and running here. As for communication, it's fine to use a phone text to do something like set up a meeting, but for substantive discussions, if you don't want to use the Git Issues board for everything, you should set up a Slack workspace and invite Shannon and me to join it. That way we will be in the loop and can answer questions, and you can tag with @ on questions where you want our input. Also, Slack can be used both as a computer app and as a phone app, so you can copy and paste bits of code directly from your screen or share files while working on computer but you can also carry on conversations through the phone app for convenience if you're away from your computer. Topics can be sorted into separate channels so it gets less messy, and it shows you where you have unread messages. So if you want to use something other than GitHub issues to converse, that would be my recommendation. It's a very easy tool to learn if you don't know it already.
