### ISSUE TITLE
comments/suggestions

### ISSUE THREAD

**Issue by haggis78** [jer179/Avatar#4]
Your graph counts the number of speeches across the episodes, which is good, but it's also possible to use string-length() to count the length of speeches. In some episodes, perhaps (say) Jon has more lines, but they're all short, and Daenerys has fewer lines, but they're longer. This would be a different, and perhaps more accurate, way of comparing how much each character speaks.

**Comment by smdunn921** [comment]
@haggis78 is this suggestion supposed to be for [GOT](https://github.com/tlr39/GOT)?

**Comment by haggis78** [comment]
@smdunn921 Oh, heck, yes it is. Sorry!
